repos:

- repo: https://github.com/tekwizely/pre-commit-golang
  rev: master
  hooks:
  - id: go-test-mod
    name: Test Go
  - id: golangci-lint-mod
    name: Lint Go

- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.16
  hooks:
  - id: circleci-config-validate
    name: Validate CircleCI
  - id: shellcheck
    name: Lint Shell Scripts

- repo: https://github.com/yelp/detect-secrets.git
  rev: v0.13.1
  hooks:
  -   id: detect-secrets
      name: Detect Secrets (Yelp)
      args: ['--baseline', '.secrets.baseline']
      exclude: .*/go.sum

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
    - id: flake8
