apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: customers
  insecureRegistries:
  - localhost:32000

test:
  - image: customers
    structureTests:
      - structure.yml
deploy:
  kubectl:
    manifests:
      - k8s/*
profiles:
- name: dev # Unrestricted Cloud dev env
- name: pub # Only via the pipeline
