server:
  port: 1102
  mode: debug
  timeouts:
    read: 30m
    write: 30m
    hammer: 2m
logging:
  level: debug
db:
  customers:
    type: postgres
    limits:
      maxIdle: 5
      maxOpen: 100
      maxLifetime: 1h
    retries:
      attempts: 3
      delay: 1ms
