server:
  port: 1102
  mode: release
  timeouts:
    read: 30m
    write: 30m
    hammer: 2m
  cors:
    allow_origins:
      - "*"
    allow_methods:
      - GET
      - POST
    allow_headers:
      - Origin
    expose_headers:
      - Content-Length
    allow_credentials: true
    max_age: 12h
logging:
  level: info
db:
  customers:
    type: postgres
    limits:
      maxIdle: 5
      maxOpen: 100
      maxLifetime: 1h
    retries:
      attempts: 5
      delay: 3s
