server:
  port: 1102
  mode: info
  timeouts:
    read: 15s
    write: 15s
    hammer: 30m
  cors:
    allow_origins:
      - "*"
    allow_methods:
      - GET
      - POST
    allow_headers:
      - Origin
    expose_headers:
      - Content-Length
    allow_credentials: true
    max_age: 12h
logging:
  level: warn
db:
  customers:
    type: postgres
    limits:
      maxIdle: 10
      maxOpen: 75
      maxLifetime: 10m
    retries:
      attempts: 20
      delay: 5s
